### ISSUE TITLE
Sample / Docs 

### ISSUE THREAD

**Issue by pierceboggan** [Rodolfocartas/PayPalMobileXamarinBindings#1]
Hi Rodolfo,

Do you by chance have a sample and accompanying documentation for this library? Would love to use it in my app, but no idea how. :)

Thanks,
Pierce Boggan

**Comment by Rodolfocartas** [comment]
Hello Pierce. The only documentation available is the one you can get from the original project.

Regards,
R.

**Comment by pierceboggan** [comment]
Hi @Rodolfocartas,

Thanks! I've updated the bindings to the latest PayPal SDK, and they work great, except for one thing. Once I get this figured out, I'll commit a sample app to the repo. :+1: 

As of right now, whenever I try to use either the sandbox or live environment, I'm getting an error saying that this is due to invalid client credentials. However, I'm copying the Client ID directly from the PayPal Developer page as seen here:
![image](https://cloud.githubusercontent.com/assets/1091304/7238507/8aea66de-e768-11e4-8afa-6a5a3bc7f7cc.png)

Here is a screenshot of my application using that Sandbox Client ID (in AppDelegate.cs):
![image](https://cloud.githubusercontent.com/assets/1091304/7238501/85964dec-e768-11e4-9c5f-c17abf5e822b.png)

Finally, here is a screenshot of me using the correct environment to preconnect:
![image](https://cloud.githubusercontent.com/assets/1091304/7238542/c4a74c98-e768-11e4-8b3e-dd03c66deccd.png)

Do you have any advice / solutions? My credentials work fine in the Obj-C/Swift implementation, but not the bindings. Hoping I can get this sorted out (for my senior design class), then I can commit a sample and some docs. :smile: 

Thanks,
Pierce Boggan

**Comment by pierceboggan** [comment]
If you can help me, I wouldn't mind tipping a bit. :)

**Comment by pierceboggan** [comment]
Figured it out. :)
